name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  create-test-container:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./.github/workflows/Dockerfile
          push: true
          tags: remiangenieux/test-bashckup:debian

  container-job:
    needs: create-test-container
    runs-on: ubuntu-latest
    container:
      using: 'docker'
      image: 'remiangenieux/test-bashckup:debian'
    steps:
      - uses: actions/checkout@v3
      - name: Install app
        run: |
          pip install .
          pip install .[tests]
      - name: Run Tests
        run: |
          pytest
